const mongoose = require('mongoose');
const Flight = require('./src/models/Flight');
require('dotenv').config();

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27020/kayak_flights';

const flights = [
  {
    flightId: 'AA101',
    airline: 'American Airlines',
    departureAirport: { code: 'JFK', name: 'John F. Kennedy International', city: 'New York', country: 'USA' },
    arrivalAirport: { code: 'LAX', name: 'Los Angeles International', city: 'Los Angeles', country: 'USA' },
    departureDateTime: new Date('2025-12-15T08:00:00'),
    arrivalDateTime: new Date('2025-12-15T11:30:00'),
    duration: { hours: 5, minutes: 30 },
    flightClass: 'Economy',
    ticketPrice: 299.99,
    totalAvailableSeats: 60,
    availableSeats: 45,
    returnFlightId: 'AA102',
    returnDepartureDateTime: new Date('2025-12-20T14:00:00'),
    returnArrivalDateTime: new Date('2025-12-20T22:30:00'),
    returnDuration: { hours: 5, minutes: 30 },
    returnTicketPrice: 299.99,
    returnFlightClass: 'Economy',
    returnTotalAvailableSeats: 60,
    returnAvailableSeats: 45,
    amenities: ['WiFi', 'Entertainment', 'Meal']
  },
  {
    flightId: 'DL201',
    airline: 'Delta Airlines',
    departureAirport: { code: 'ATL', name: 'Hartsfield-Jackson Atlanta International', city: 'Atlanta', country: 'USA' },
    arrivalAirport: { code: 'MIA', name: 'Miami International', city: 'Miami', country: 'USA' },
    departureDateTime: new Date('2025-12-16T10:00:00'),
    arrivalDateTime: new Date('2025-12-16T12:15:00'),
    duration: { hours: 2, minutes: 15 },
    flightClass: 'Business',
    ticketPrice: 499.99,
    totalAvailableSeats: 30,
    availableSeats: 20,
    returnFlightId: 'DL202',
    returnDepartureDateTime: new Date('2025-12-21T15:00:00'),
    returnArrivalDateTime: new Date('2025-12-21T17:15:00'),
    returnDuration: { hours: 2, minutes: 15 },
    returnTicketPrice: 499.99,
    returnFlightClass: 'Business',
    returnTotalAvailableSeats: 30,
    returnAvailableSeats: 20,
    amenities: ['WiFi', 'Entertainment', 'Premium Meal', 'Priority Boarding']
  },
  {
    flightId: 'UA301',
    airline: 'United Airlines',
    departureAirport: { code: 'ORD', name: 'O\'Hare International', city: 'Chicago', country: 'USA' },
    arrivalAirport: { code: 'SFO', name: 'San Francisco International', city: 'San Francisco', country: 'USA' },
    departureDateTime: new Date('2025-12-17T09:00:00'),
    arrivalDateTime: new Date('2025-12-17T11:45:00'),
    duration: { hours: 4, minutes: 45 },
    flightClass: 'Economy',
    ticketPrice: 349.99,
    totalAvailableSeats: 60,
    availableSeats: 50,
    returnFlightId: 'UA302',
    returnDepartureDateTime: new Date('2025-12-22T13:00:00'),
    returnArrivalDateTime: new Date('2025-12-22T19:45:00'),
    returnDuration: { hours: 4, minutes: 45 },
    returnTicketPrice: 349.99,
    returnFlightClass: 'Economy',
    returnTotalAvailableSeats: 60,
    returnAvailableSeats: 50,
    amenities: ['WiFi', 'Entertainment']
  },
  {
    flightId: 'SW401',
    airline: 'Southwest Airlines',
    departureAirport: { code: 'DAL', name: 'Dallas Love Field', city: 'Dallas', country: 'USA' },
    arrivalAirport: { code: 'DEN', name: 'Denver International', city: 'Denver', country: 'USA' },
    departureDateTime: new Date('2025-12-18T07:00:00'),
    arrivalDateTime: new Date('2025-12-18T09:30:00'),
    duration: { hours: 2, minutes: 30 },
    flightClass: 'Economy',
    ticketPrice: 199.99,
    totalAvailableSeats: 60,
    availableSeats: 40,
    returnFlightId: 'SW402',
    returnDepartureDateTime: new Date('2025-12-23T11:00:00'),
    returnArrivalDateTime: new Date('2025-12-23T13:30:00'),
    returnDuration: { hours: 2, minutes: 30 },
    returnTicketPrice: 199.99,
    returnFlightClass: 'Economy',
    returnTotalAvailableSeats: 60,
    returnAvailableSeats: 40,
    amenities: ['WiFi']
  },
  {
    flightId: 'JB501',
    airline: 'JetBlue Airways',
    departureAirport: { code: 'BOS', name: 'Logan International', city: 'Boston', country: 'USA' },
    arrivalAirport: { code: 'SEA', name: 'Seattle-Tacoma International', city: 'Seattle', country: 'USA' },
    departureDateTime: new Date('2025-12-19T06:00:00'),
    arrivalDateTime: new Date('2025-12-19T09:15:00'),
    duration: { hours: 6, minutes: 15 },
    flightClass: 'Economy',
    ticketPrice: 399.99,
    totalAvailableSeats: 60,
    availableSeats: 35,
    returnFlightId: 'JB502',
    returnDepartureDateTime: new Date('2025-12-24T10:00:00'),
    returnArrivalDateTime: new Date('2025-12-24T18:15:00'),
    returnDuration: { hours: 6, minutes: 15 },
    returnTicketPrice: 399.99,
    returnFlightClass: 'Economy',
    returnTotalAvailableSeats: 60,
    returnAvailableSeats: 35,
    amenities: ['WiFi', 'Entertainment', 'Snacks']
  },
  {
    flightId: 'AA601',
    airline: 'American Airlines',
    departureAirport: { code: 'PHX', name: 'Phoenix Sky Harbor International', city: 'Phoenix', country: 'USA' },
    arrivalAirport: { code: 'LAS', name: 'McCarran International', city: 'Las Vegas', country: 'USA' },
    departureDateTime: new Date('2025-12-20T08:30:00'),
    arrivalDateTime: new Date('2025-12-20T09:45:00'),
    duration: { hours: 1, minutes: 15 },
    flightClass: 'Economy',
    ticketPrice: 149.99,
    totalAvailableSeats: 60,
    availableSeats: 55,
    returnFlightId: 'AA602',
    returnDepartureDateTime: new Date('2025-12-25T16:00:00'),
    returnArrivalDateTime: new Date('2025-12-25T17:15:00'),
    returnDuration: { hours: 1, minutes: 15 },
    returnTicketPrice: 149.99,
    returnFlightClass: 'Economy',
    returnTotalAvailableSeats: 60,
    returnAvailableSeats: 55,
    amenities: ['WiFi']
  },
  {
    flightId: 'DL701',
    airline: 'Delta Airlines',
    departureAirport: { code: 'MSP', name: 'Minneapolis-Saint Paul International', city: 'Minneapolis', country: 'USA' },
    arrivalAirport: { code: 'DTW', name: 'Detroit Metropolitan', city: 'Detroit', country: 'USA' },
    departureDateTime: new Date('2025-12-21T11:00:00'),
    arrivalDateTime: new Date('2025-12-21T13:30:00'),
    duration: { hours: 1, minutes: 30 },
    flightClass: 'Business',
    ticketPrice: 449.99,
    totalAvailableSeats: 30,
    availableSeats: 25,
    returnFlightId: 'DL702',
    returnDepartureDateTime: new Date('2025-12-26T14:00:00'),
    returnArrivalDateTime: new Date('2025-12-26T15:30:00'),
    returnDuration: { hours: 1, minutes: 30 },
    returnTicketPrice: 449.99,
    returnFlightClass: 'Business',
    returnTotalAvailableSeats: 30,
    returnAvailableSeats: 25,
    amenities: ['WiFi', 'Entertainment', 'Premium Meal']
  },
  {
    flightId: 'UA801',
    airline: 'United Airlines',
    departureAirport: { code: 'IAH', name: 'George Bush Intercontinental', city: 'Houston', country: 'USA' },
    arrivalAirport: { code: 'PHL', name: 'Philadelphia International', city: 'Philadelphia', country: 'USA' },
    departureDateTime: new Date('2025-12-22T12:00:00'),
    arrivalDateTime: new Date('2025-12-22T15:30:00'),
    duration: { hours: 3, minutes: 30 },
    flightClass: 'Economy',
    ticketPrice: 279.99,
    totalAvailableSeats: 60,
    availableSeats: 48,
    returnFlightId: 'UA802',
    returnDepartureDateTime: new Date('2025-12-27T16:00:00'),
    returnArrivalDateTime: new Date('2025-12-27T19:30:00'),
    returnDuration: { hours: 3, minutes: 30 },
    returnTicketPrice: 279.99,
    returnFlightClass: 'Economy',
    returnTotalAvailableSeats: 60,
    returnAvailableSeats: 48,
    amenities: ['WiFi', 'Entertainment']
  },
  {
    flightId: 'SW901',
    airline: 'Southwest Airlines',
    departureAirport: { code: 'BWI', name: 'Baltimore/Washington International', city: 'Baltimore', country: 'USA' },
    arrivalAirport: { code: 'CLT', name: 'Charlotte Douglas International', city: 'Charlotte', country: 'USA' },
    departureDateTime: new Date('2025-12-23T09:00:00'),
    arrivalDateTime: new Date('2025-12-23T10:30:00'),
    duration: { hours: 1, minutes: 30 },
    flightClass: 'Economy',
    ticketPrice: 179.99,
    totalAvailableSeats: 60,
    availableSeats: 42,
    returnFlightId: 'SW902',
    returnDepartureDateTime: new Date('2025-12-28T12:00:00'),
    returnArrivalDateTime: new Date('2025-12-28T13:30:00'),
    returnDuration: { hours: 1, minutes: 30 },
    returnTicketPrice: 179.99,
    returnFlightClass: 'Economy',
    returnTotalAvailableSeats: 60,
    returnAvailableSeats: 42,
    amenities: ['WiFi']
  },
  {
    flightId: 'JB1001',
    airline: 'JetBlue Airways',
    departureAirport: { code: 'FLL', name: 'Fort Lauderdale-Hollywood International', city: 'Fort Lauderdale', country: 'USA' },
    arrivalAirport: { code: 'JFK', name: 'John F. Kennedy International', city: 'New York', country: 'USA' },
    departureDateTime: new Date('2025-12-24T07:00:00'),
    arrivalDateTime: new Date('2025-12-24T10:00:00'),
    duration: { hours: 3, minutes: 0 },
    flightClass: 'Economy',
    ticketPrice: 249.99,
    totalAvailableSeats: 60,
    availableSeats: 38,
    returnFlightId: 'JB1002',
    returnDepartureDateTime: new Date('2025-12-29T11:00:00'),
    returnArrivalDateTime: new Date('2025-12-29T14:00:00'),
    returnDuration: { hours: 3, minutes: 0 },
    returnTicketPrice: 249.99,
    returnFlightClass: 'Economy',
    returnTotalAvailableSeats: 60,
    returnAvailableSeats: 38,
    amenities: ['WiFi', 'Entertainment', 'Snacks']
  },
  {
    flightId: 'AA1101',
    airline: 'American Airlines',
    departureAirport: { code: 'SLC', name: 'Salt Lake City International', city: 'Salt Lake City', country: 'USA' },
    arrivalAirport: { code: 'PDX', name: 'Portland International', city: 'Portland', country: 'USA' },
    departureDateTime: new Date('2025-12-25T10:00:00'),
    arrivalDateTime: new Date('2025-12-25T11:30:00'),
    duration: { hours: 1, minutes: 30 },
    flightClass: 'First',
    ticketPrice: 599.99,
    totalAvailableSeats: 20,
    availableSeats: 15,
    returnFlightId: 'AA1102',
    returnDepartureDateTime: new Date('2025-12-30T13:00:00'),
    returnArrivalDateTime: new Date('2025-12-30T14:30:00'),
    returnDuration: { hours: 1, minutes: 30 },
    returnTicketPrice: 599.99,
    returnFlightClass: 'First',
    returnTotalAvailableSeats: 20,
    returnAvailableSeats: 15,
    amenities: ['WiFi', 'Entertainment', 'Gourmet Meal', 'Lounge Access', 'Priority Boarding']
  },
  {
    flightId: 'DL1201',
    airline: 'Delta Airlines',
    departureAirport: { code: 'MCO', name: 'Orlando International', city: 'Orlando', country: 'USA' },
    arrivalAirport: { code: 'BNA', name: 'Nashville International', city: 'Nashville', country: 'USA' },
    departureDateTime: new Date('2025-12-26T08:00:00'),
    arrivalDateTime: new Date('2025-12-26T10:00:00'),
    duration: { hours: 2, minutes: 0 },
    flightClass: 'Economy',
    ticketPrice: 229.99,
    totalAvailableSeats: 60,
    availableSeats: 50,
    returnFlightId: 'DL1202',
    returnDepartureDateTime: new Date('2025-12-31T12:00:00'),
    returnArrivalDateTime: new Date('2025-12-31T14:00:00'),
    returnDuration: { hours: 2, minutes: 0 },
    returnTicketPrice: 229.99,
    returnFlightClass: 'Economy',
    returnTotalAvailableSeats: 60,
    returnAvailableSeats: 50,
    amenities: ['WiFi', 'Entertainment']
  },
  {
    flightId: 'UA1301',
    airline: 'United Airlines',
    departureAirport: { code: 'STL', name: 'Lambert-St. Louis International', city: 'St. Louis', country: 'USA' },
    arrivalAirport: { code: 'CLE', name: 'Cleveland Hopkins International', city: 'Cleveland', country: 'USA' },
    departureDateTime: new Date('2025-12-27T09:00:00'),
    arrivalDateTime: new Date('2025-12-27T11:00:00'),
    duration: { hours: 2, minutes: 0 },
    flightClass: 'Economy',
    ticketPrice: 199.99,
    totalAvailableSeats: 60,
    availableSeats: 45,
    returnFlightId: 'UA1302',
    returnDepartureDateTime: new Date('2026-01-01T13:00:00'),
    returnArrivalDateTime: new Date('2026-01-01T15:00:00'),
    returnDuration: { hours: 2, minutes: 0 },
    returnTicketPrice: 199.99,
    returnFlightClass: 'Economy',
    returnTotalAvailableSeats: 60,
    returnAvailableSeats: 45,
    amenities: ['WiFi']
  },
  {
    flightId: 'SW1401',
    airline: 'Southwest Airlines',
    departureAirport: { code: 'HOU', name: 'William P. Hobby', city: 'Houston', country: 'USA' },
    arrivalAirport: { code: 'AUS', name: 'Austin-Bergstrom International', city: 'Austin', country: 'USA' },
    departureDateTime: new Date('2025-12-28T07:00:00'),
    arrivalDateTime: new Date('2025-12-28T08:15:00'),
    duration: { hours: 1, minutes: 15 },
    flightClass: 'Economy',
    ticketPrice: 129.99,
    totalAvailableSeats: 60,
    availableSeats: 52,
    returnFlightId: 'SW1402',
    returnDepartureDateTime: new Date('2026-01-02T10:00:00'),
    returnArrivalDateTime: new Date('2026-01-02T11:15:00'),
    returnDuration: { hours: 1, minutes: 15 },
    returnTicketPrice: 129.99,
    returnFlightClass: 'Economy',
    returnTotalAvailableSeats: 60,
    returnAvailableSeats: 52,
    amenities: ['WiFi']
  },
  {
    flightId: 'JB1501',
    airline: 'JetBlue Airways',
    departureAirport: { code: 'RDU', name: 'Raleigh-Durham International', city: 'Raleigh', country: 'USA' },
    arrivalAirport: { code: 'TPA', name: 'Tampa International', city: 'Tampa', country: 'USA' },
    departureDateTime: new Date('2025-12-29T08:00:00'),
    arrivalDateTime: new Date('2025-12-29T10:00:00'),
    duration: { hours: 2, minutes: 0 },
    flightClass: 'Economy',
    ticketPrice: 219.99,
    totalAvailableSeats: 60,
    availableSeats: 40,
    returnFlightId: 'JB1502',
    returnDepartureDateTime: new Date('2026-01-03T11:00:00'),
    returnArrivalDateTime: new Date('2026-01-03T13:00:00'),
    returnDuration: { hours: 2, minutes: 0 },
    returnTicketPrice: 219.99,
    returnFlightClass: 'Economy',
    returnTotalAvailableSeats: 60,
    returnAvailableSeats: 40,
    amenities: ['WiFi', 'Entertainment']
  },
  {
    flightId: 'AA1601',
    airline: 'American Airlines',
    departureAirport: { code: 'IND', name: 'Indianapolis International', city: 'Indianapolis', country: 'USA' },
    arrivalAirport: { code: 'CMH', name: 'John Glenn Columbus International', city: 'Columbus', country: 'USA' },
    departureDateTime: new Date('2025-12-30T09:00:00'),
    arrivalDateTime: new Date('2025-12-30T10:30:00'),
    duration: { hours: 1, minutes: 30 },
    flightClass: 'Business',
    ticketPrice: 399.99,
    totalAvailableSeats: 30,
    availableSeats: 22,
    returnFlightId: 'AA1602',
    returnDepartureDateTime: new Date('2026-01-04T12:00:00'),
    returnArrivalDateTime: new Date('2026-01-04T13:30:00'),
    returnDuration: { hours: 1, minutes: 30 },
    returnTicketPrice: 399.99,
    returnFlightClass: 'Business',
    returnTotalAvailableSeats: 30,
    returnAvailableSeats: 22,
    amenities: ['WiFi', 'Entertainment', 'Premium Meal']
  },
  {
    flightId: 'DL1701',
    airline: 'Delta Airlines',
    departureAirport: { code: 'MCI', name: 'Kansas City International', city: 'Kansas City', country: 'USA' },
    arrivalAirport: { code: 'MEM', name: 'Memphis International', city: 'Memphis', country: 'USA' },
    departureDateTime: new Date('2025-12-31T10:00:00'),
    arrivalDateTime: new Date('2025-12-31T11:45:00'),
    duration: { hours: 1, minutes: 45 },
    flightClass: 'Economy',
    ticketPrice: 189.99,
    totalAvailableSeats: 60,
    availableSeats: 48,
    returnFlightId: 'DL1702',
    returnDepartureDateTime: new Date('2026-01-05T14:00:00'),
    returnArrivalDateTime: new Date('2026-01-05T15:45:00'),
    returnDuration: { hours: 1, minutes: 45 },
    returnTicketPrice: 189.99,
    returnFlightClass: 'Economy',
    returnTotalAvailableSeats: 60,
    returnAvailableSeats: 48,
    amenities: ['WiFi', 'Entertainment']
  },
  {
    flightId: 'UA1801',
    airline: 'United Airlines',
    departureAirport: { code: 'OAK', name: 'Oakland International', city: 'Oakland', country: 'USA' },
    arrivalAirport: { code: 'SAN', name: 'San Diego International', city: 'San Diego', country: 'USA' },
    departureDateTime: new Date('2026-01-01T08:00:00'),
    arrivalDateTime: new Date('2026-01-01T09:30:00'),
    duration: { hours: 1, minutes: 30 },
    flightClass: 'Economy',
    ticketPrice: 179.99,
    totalAvailableSeats: 60,
    availableSeats: 55,
    returnFlightId: 'UA1802',
    returnDepartureDateTime: new Date('2026-01-06T11:00:00'),
    returnArrivalDateTime: new Date('2026-01-06T12:30:00'),
    returnDuration: { hours: 1, minutes: 30 },
    returnTicketPrice: 179.99,
    returnFlightClass: 'Economy',
    returnTotalAvailableSeats: 60,
    returnAvailableSeats: 55,
    amenities: ['WiFi']
  },
  {
    flightId: 'SW1901',
    airline: 'Southwest Airlines',
    departureAirport: { code: 'MDW', name: 'Midway International', city: 'Chicago', country: 'USA' },
    arrivalAirport: { code: 'MKE', name: 'General Mitchell International', city: 'Milwaukee', country: 'USA' },
    departureDateTime: new Date('2026-01-02T07:00:00'),
    arrivalDateTime: new Date('2026-01-02T08:00:00'),
    duration: { hours: 1, minutes: 0 },
    flightClass: 'Economy',
    ticketPrice: 119.99,
    totalAvailableSeats: 60,
    availableSeats: 58,
    returnFlightId: 'SW1902',
    returnDepartureDateTime: new Date('2026-01-07T10:00:00'),
    returnArrivalDateTime: new Date('2026-01-07T11:00:00'),
    returnDuration: { hours: 1, minutes: 0 },
    returnTicketPrice: 119.99,
    returnFlightClass: 'Economy',
    returnTotalAvailableSeats: 60,
    returnAvailableSeats: 58,
    amenities: ['WiFi']
  },
  {
    flightId: 'JB2001',
    airline: 'JetBlue Airways',
    departureAirport: { code: 'PIT', name: 'Pittsburgh International', city: 'Pittsburgh', country: 'USA' },
    arrivalAirport: { code: 'BUF', name: 'Buffalo Niagara International', city: 'Buffalo', country: 'USA' },
    departureDateTime: new Date('2026-01-03T09:00:00'),
    arrivalDateTime: new Date('2026-01-03T10:15:00'),
    duration: { hours: 1, minutes: 15 },
    flightClass: 'Economy',
    ticketPrice: 159.99,
    totalAvailableSeats: 60,
    availableSeats: 50,
    returnFlightId: 'JB2002',
    returnDepartureDateTime: new Date('2026-01-08T12:00:00'),
    returnArrivalDateTime: new Date('2026-01-08T13:15:00'),
    returnDuration: { hours: 1, minutes: 15 },
    returnTicketPrice: 159.99,
    returnFlightClass: 'Economy',
    returnTotalAvailableSeats: 60,
    returnAvailableSeats: 50,
    amenities: ['WiFi', 'Entertainment', 'Snacks']
  }
];

async function seedFlights() {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log('Connected to MongoDB');

    // Clear existing flights
    await Flight.deleteMany({});
    console.log('Cleared existing flights');

    // Insert new flights
    const insertedFlights = await Flight.insertMany(flights);
    console.log(`✅ Seeded ${insertedFlights.length} flights successfully!`);

    await mongoose.connection.close();
    console.log('Database connection closed');
  } catch (error) {
    console.error('Error seeding flights:', error);
    process.exit(1);
  }
}

seedFlights();

